# Configures Netflify CMS
backend: 
  name: test-repo

media_folder: static/assets

collections:
  # type of collection
  - name: post
    label: Posts
    # where the markdown files are stored
    folder: src/posts
    #bool allow to create new files
    create: true
    # Fields for CMS form
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
